apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: assembleia-votacao
data:
  spring.datasource.url: "jdbc:h2:file:/app/data/votacao_db;DB_CLOSE_ON_EXIT=FALSE"
  spring.datasource.driver-class-name: "org.h2.Driver"
  spring.h2.console.enabled: "true"
  spring.h2.console.path: "/h2-console"
  spring.h2.console.settings.web-allow-others: "true"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.show-sql: "false"
  launcher.ui.disabled: "true"
